### PR TITLE
Removing native PolyClipper and adopting standalone PolyClipper library as third party source

### PR DESCRIPTION
**Pull request by jmikeowen**
This pull request converts Spheral to using the standalone PolyClipper library as a third party library.  Previous to this change we were using native Spheral implementations of the methods currently in PolyClipper (since PolyClipper started as internal to Spheral code), but now PolyClipper has new bugfixes and features not found in our internal source.

### CODE REVIEW

**Comment by mdavis36** [comment]
What happened to the Polyclipper namespace? Does polyclipper just preface all of it's types with Polyclipper now?

**Comment by jmikeowen** [comment]
I was just going to respond to Mike's question, but I see he found the answer.  I do have some typedef's in Spheral to remove some of the template argument typing, since the new PolyClipper uses templates to support directly using the host code native Vector types.  These things are a tradeoff -- typedefs can make things clearer by shortening statements and removing redundant arguments, but you have to know what they really mean under the hood.

**Comment by jmikeowen** [comment]
I'm converting this to a draft until I get the Spheral based PolyClipper unit tests sorted.

**Comment by mdavis36** [comment]
I'm getting some failed tests on TensileRod-1D and 2 instances of CollisionlessSphereCollapse. I'm running TensileRod-1D standalone to try and dig up the issue but it seems to only fail when run through ats and not ./spheral? CollisionlessSphereCollapse is failing with "Memory error : std::bad_alloc". Looking into this further.

**Comment by jmikeowen** [comment]
I don't understand what's happening there -- all those tests pass for me on rzgenie run with "lcats".  How/where are you running them?  You can also run individual tests with the ATS as well, so "lcats -e <your spheral> TensileRod-1d.py" for instance.

**Comment by jmikeowen** [comment]
Shoot, the markup absorbed some of my line there, that should have been "lcats -e your_spheral TensileRod-1d.py"

**Review by mdavis36 — APPROVED** [review]

**Review by MishaZakharchanka — APPROVED** [review]

**Pull request merged**
