### PR TITLE
Update building.rst

### PR DESCRIPTION
**Pull request by as1m0n**
1) Changed "chdir" to more universal "cd"
2) changed ../../spheral to ../../Spheral to match current setup

### CODE REVIEW

**Comment by jmikeowen** [comment]
The "cd" change seems reasonable (this is shell dependent, but probably more folks are using bash these days).  But the default clone of Spheral drops in a directory called "spheral" with the lower-case s doesn't it?

**Comment by as1m0n** [comment]
Mike,

On my system (Windows 10 with WSL2, Ubuntu 20.04) there are two folders, 
Spheral (after git clone etc...) and Spheral_Release (after the script 
mkdir, etc.).
Is there a 3rd folder "spheral" that should be made? There is no 
"../../spheral".

Andy

------ Original Message ------

**Comment by as1m0n** [comment]
I ran the "git clone --recursive https://github.com/jmikeowen/Spheral" 
and it places everything into "Spheral".

Andy

------ Original Message ------

**Comment by jmikeowen** [comment]
Ah, I see the difference.   If you use the clone command that the GitHub site offers up on the "Download" button, it comes out lower-case.  But, because I wrote the upper-case Spheral in the docs you're getting it that way.  This makes your change to the docs more consistent, so we should stick with that.

**Review by jmikeowen — APPROVED** [review]
This is more consistent with bash, which is a common shell, so looks good.

**Pull request merged**
