### PR TITLE
Eos update

### PR DESCRIPTION
**Pull request by jmpearl**
The GamaLaw and Polytropic EOS's were using the isothermal bulk modulus. I switched them over to the isentropic bulk modulus to be more consistent w/ the Solid EOS's.

### CODE REVIEW

**Review by jmikeowen — APPROVED** [review]
Huh, didn't realize these were off.

**Comment by jmpearl** [comment]
wow, I'm just really testing out gitlab ci's defenses here guess I aught to bump this to a draft

**Comment by jmpearl** [comment]
scratch that ci just didn't get resources

**Review by jmikeowen — APPROVED** [review]
Upping the tolerance on this test seems necessary.  Hopefully it'll pass more reliably now.

**Pull request merged**
