### PR TITLE
Move KernelIntegrator to Spheral

### PR DESCRIPTION
**Pull request by brbass**
This adds the KernelIntegrator package, which performs spatial integration of the meshless kernels.

### CODE REVIEW

**Comment by mdavis36** [comment]
There is a bug in the CI where we are getting false positives on some builds. Although it says the non mpi builds are passing they are silently failing due to some unguarded MPI references.

**Comment by brbass** [comment]
The tests are all passing except an unrelated unit test below, so this PR should be ready for review. 

blueos_gcc_8_3_1_spectrum_test
    FAIL testBiLinearInterpolator(BiLinearInterpolator unit tests) 26.60 sec

**Comment by mdavis36** [comment]
@brbass Please ensure the LLNLSpheral PR is up to date and passes all tests with this branch

**Review by mdavis36 — APPROVED** [review]

**Review by jmikeowen — APPROVED** [review]
Looking good.  Just need to merge the latest from develop.

**Review by MishaZakharchanka — APPROVED** [review]

**Pull request merged**
