### PR TITLE
Added NodeList index to DataBase

### PR DESCRIPTION
**Pull request by brbass**
This lets us calculate the index in the `DataBase` that represents a given `NodeList` in the connectivity. 

### ToDo :

- [X] Annotate ``RELEASE_NOTES.md`` with notable changes.
- [X] Create LLNLSpheral PR pointing at this branch. (PR#113)
- [ ] LLNLSpheral PR has passed all tests.

### CODE REVIEW

**Review by jmikeowen — APPROVED** [review]
This looks fine.  A heads up for the future -- I've been slowly transitioning things like this from int to size_t, which I now know is the more appropriate type for sizes and indices into containers like this.  The int here is fine for now though, and consistent with the other things that return int's in the DataBase interface.

**Comment by mdavis36** [comment]
@brbass I know you didn't want to create a separate LLNL PR for this. However, if you could have [#PR113](https://rzlc.llnl.gov/gitlab/owen/LLNLSpheral/-/merge_requests/113) point to this branch we can consider the LLNLSpheral requirement for this PR satisfied when both pass.

**Comment by brbass** [comment]
> @brbass I know you didn't want to create a separate LLNL PR for this. However, if you could have [#PR113](https://rzlc.llnl.gov/gitlab/owen/LLNLSpheral/-/merge_requests/113) point to this branch we can consider the LLNLSpheral requirement for this PR satisfied when both pass.

That MR is pointing at this one already. We should wait until that one is ready in case I need to make other changes.

**Review by jmikeowen — APPROVED** [review]
These seem good

**Pull request merged**
