### PR TITLE
Always include the git hash in the Spheral python banner

### PR DESCRIPTION
**Pull request by ldowen**
# Summary

- This PR is a bugfix
- It does the following:
  - Ensures the git hash is always displayed in the Spheral python banner

------
### ToDo :

- [x] Annotate ``RELEASE_NOTES.md`` with notable changes.
- [x] Create LLNLSpheral PR pointing at this branch. (PR#70)
- [ ] LLNLSpheral PR has passed all tests.

### CODE REVIEW

**Comment by mdavis36** [comment]
@ldowen @jmikeowen If this is ready, can we run a test install with a tag e.g. "risky-test" to ensure this works as intended on production installs.

**Comment by jmikeowen** [comment]
@mdavis36 @ldowen , I agree it would be great to test with a tag as Mike suggests.  Can we do that still in the branch?

**Comment by mdavis36** [comment]
@ldowen @jmikeowen It will trigger the pipeline for a tag on any branch. We just need to go in and manually trigger the production jobs for the installation once the pipeline has started and completed the normal set of build and test jobs.

**Comment by mdavis36** [comment]
@ldowen @jmikeowen Looks good to go
```
davis291@ruby965(master):[~]: ml load Spheral/risky-test
davis291@ruby965(master):[~]: spheral -c "import Spheral"
/------------------------------------------------------------------------------\
|  Spheral version             : risky-test b30b4fb3d HEAD                     |
|    number of MPI tasks       : 1                                             |
|    number of threads per rank: 56                                            |
\------------------------------------------------------------------------------/
```

**Review by mdavis36 — APPROVED** [review]

**Pull request merged**
