### PR TITLE
Fix ats & gnuplot install bug.

### LINKED ISSUE #72: Errors in creating Spheral virtual python environment: PolyClipper.so not found!
Everything goes well when I run `make`, except the last step in creating Spheral virtual python environment.

I searched the `Spheral_release` directory and did not found the `so` file elsewhere.

Could someone point out why this happened, or tell me how to find the reason?

```
Creating Spheral virtual python environment ...
created virtual environment CPython2.7.18.final.0-64 in 3333ms
  creator CPython2Posix(dest=/home/liuchang/soft/Spheral_release/.venv, clear=False, no_vcs_ignore=False, global=True)
  seeder FromAppData(download=False, pip=bundle, wheel=bundle, setuptools=bundle, via=copy, app_data_dir=/home/liuchang/.local/share/virtualenv)
    added seed packages: pip==20.3.1, setuptools==44.1.1, wheel==0.36.1
  activators PythonActivator,CShellActivator,FishActivator,PowerShellActivator,BashActivator
Installing Spheral ...
cp: cannot stat ‘/home/liuchang/soft/Spheral_release/tpl/polyclipper/511684c4b491a06d2b0eac53cc11fd02/PolyClipper.so’: No such file or directory
Installing Gnuplot, ats ...
cp: cannot stat ‘/home/liuchang/soft/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/Gnuplot’: No such file or directory
cp: cannot stat ‘/home/liuchang/soft/Spheral_release/tpl/python/38c84292658ed4456157195f1c9bcbe1/lib/python2.7/site-packages/ats’: No such file or directory
Creating spheral symlink to spheral-env script ...
```

[make-install.log](https://github.com/LLNL/spheral/files/6705901/build.log)

### PR DESCRIPTION
**Pull request by mdavis36**
# Summary 
This PR fixes #72 : 
 - Fixes typo in Install_Python_distutils_library.cmake.
 - Add pip module dependencies for building ats & gnuplot.
 - Remove PolyClipper.so library copy to site-packages/ (no longer building).

### CODE REVIEW

**Review by MishaZakharchanka — APPROVED** [review]

**Comment by jmikeowen** [comment]
I'm trying to try this out, but I'm getting some strange TPL complaints during the cmake configuration.  It looks like it's trying to install TPLs to "/usr/local/tpl" rather than the install target directory, and the cmake process fails with errors like:

Generating build process for aneos.
aneos_DIR not set. Installing aneos to default location : /usr/local/tpl/aneos/188f51f21b72c7c5a32a5581f3eb6be3
CMake Error at /usr/share/cmake-3.16/Modules/ExternalProject.cmake:1706 (file):
  file problem creating directory:
  /usr/local/tpl/aneos/188f51f21b72c7c5a32a5581f3eb6be3/lib

**Comment by mdavis36** [comment]
> I'm trying to try this out, but I'm getting some strange TPL complaints during the cmake configuration. It looks like it's trying to install TPLs to "/usr/local/tpl" rather than the install target directory, and the cmake process fails with errors like:
> 
> Generating build process for aneos.
> aneos_DIR not set. Installing aneos to default location : /usr/local/tpl/aneos/188f51f21b72c7c5a32a5581f3eb6be3
> CMake Error at /usr/share/cmake-3.16/Modules/ExternalProject.cmake:1706 (file):
> file problem creating directory:
> /usr/local/tpl/aneos/188f51f21b72c7c5a32a5581f3eb6be3/lib

Can you attach you cmake config command. I was using `cmake ../ -DCMAKE_INSTALL_PREFIX="../install"` from `spheral/BUILD/`with directory structure:
```
spheral
|- BUILD
|- install
|- src
|- ...
```

**Comment by jmikeowen** [comment]
Starting from the directory above the "spheral" clone:

mkdir -p optimize/BUILD
cd optimize/BUILD
cmake ../../spheral -DCMAKE_INSTALL_PRFEFIX=`chdir ..; pwd`

This leads to the confusion with the TPL path, during the cmake configure the following is printed:
...
-- Setting SPHERAL_TPL_DIR /usr/local/tpl
Default TPL location : /usr/local/tpl
....

**Comment by mdavis36** [comment]
My shell doesn't support `chdir` but with `cd` this works for me. Can you try deleting CMakeCache.txt before running again?

**Comment by jmikeowen** [comment]
Uh, yep, that was just a typo on my part.  Looks like things are OK.

**Review by jmikeowen — APPROVED** [review]

**Pull request merged**
