### PR TITLE
bugfix FSISPH and constant boundaries

### PR DESCRIPTION
**Pull request by jmpearl**
# Summary

- the damaged pressure was being initialized at 2x. This would cause issues for problems w/ constant boundaries.

------
### ToDo :

- [x] Annotate ``RELEASE_NOTES.md`` with notable changes.
- [x] Create LLNLSpheral PR pointing at this branch. (PR#)
- [x] LLNLSpheral PR has passed all tests.

### CODE REVIEW

**Review by jmikeowen — APPROVED** [review]
Assuming the damaged pressure is always otherwise initialized this is fine.  Another fix would have been to initialize here with 
mDamagedPressure = this->pressure();
rather than adding it.  Why was this done with += originally?

**Comment by jmpearl** [comment]
That is a great question and i asked myself the same thing. I can't remember why I had it as plus equals originally. I think the damaged pressure should always be initialized now through the call to the pressure update policy. Do you see any edge cases where that might not be the case?

**Comment by jmikeowen** [comment]
Naw, I think you should be good as is.  Still have to ask about having a test that would catch this error of course... :-)

**Comment by jmpearl** [comment]
I'm going to merge this now just to get the change in and punt on the test to a later date

**Pull request merged**
